credentials:
    username: user@domain.com
    
billing:
    name: John Smith
    credit_card_number: 1111222233334444
    credit_card_expiration: 01/22
    address1: 123 Broadway
    address2: 
    city: New York
    state_province: NY
    postal_code: 10000

# Trains
trains:
    - origin: NYP
      destination: WAS
      day_of_week: Thursday
      times:
          - time: 08:00
            max_price: 100
          - time: 09:00
            max_price: 100
    - origin: WAS
      destination: NYP
      day_of_week: Sunday
      times:
          - time: 20:00
            max_price: 100
          - time: 21:00
            max_price: 100